name = "Zombies"
uid = "4b113ac0-59af-11e9-b475-0800200c9a66"
version = 3
description = "Dead units will become zombies! Now with army selection and mass/energy vampire under AI Options in the lobby. See more at https://github.com/douglasg14b/FAF-Zombies"
author = "Original code by Zarechaun. Additional code by Douglasg14b, Icon by flaticon.com"
url = "https://github.com/douglasg14b/FAF-Zombies"
icon = "/mods/Zombies/modicon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
